name: "On Tag Deploy on crates.io"
env:
    REPO_NAME: "scaler"
    RUN_TESTS: true
    RUST_VERSION: "1.80"
on:
    push:
        tags:
            # -   "[0-9]+.[0-9]+.[0-9]+"
            -   "*" # execute every time tag is pushed


jobs:
    initialisation:
        name: "Initialisation"
        env:
            working-directory: ${{github.workspace}}
        runs-on: "ubuntu-latest"

        steps:
            -   name: "Checkout Repository"
                uses: "actions/checkout@v4" # makes repository structure available
                with:
                    fetch-depth: 0 # fetch all commits, so we can access all tags

            -   name: "NOW"
                id: "now"
                run: "echo \"NOW=$(date +'%Y-%m-%dT%H:%M:%S')\" >> $GITHUB_OUTPUT"  # get datetime, save in NOW, push to output

            -   name: "TAG"
                id: "tag"
                run: "echo \"TAG=$(git describe --tags --abbrev=0)\" >> $GITHUB_OUTPUT" # get tag, save in TAG, push to output

            -   name: "TAG_PREVIOUS"
                id: "tag_previous"
                run: "echo \"TAG_PREVIOUS=$(git tag --sort=-creatordate | sed -n '2p')\" >> $GITHUB_OUTPUT" # get previous tag, save in TAG_PREVIOUS, push to output

            -   name: "TODAY"
                id: "today"
                run: "echo \"TODAY=$(date +'%Y-%m-%d')\" >> $GITHUB_OUTPUT" # get date, save in TODAY, push to output

        outputs:    # set step output as job output so other jobs can access
            NOW: ${{steps.now.outputs.NOW}}
            TAG: ${{steps.tag.outputs.TAG}}
            TAG_PREVIOUS: ${{steps.tag_previous.outputs.TAG_PREVIOUS}}
            TODAY: ${{steps.today.outputs.TODAY}}


    test:
        name: "Run Tests"
        env:
            working-directory: ${{github.workspace}}
        needs: ["initialisation"]
        runs-on: "ubuntu-latest"

        steps:
            -   name: "Checkout Repository"
                uses: "actions/checkout@v4" # makes repository structure available

            -   name: "Install Rust"
                uses: "actions-rust-lang/setup-rust-toolchain@v1"
                with:
                    toolchain: ${{env.RUST_VERSION}}

            -   name: "Check Project Version and Tag Match"
                run: |
                    project_version=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
                    if [ "$project_version" == "${{needs.initialisation.outputs.TAG}}" ]; then
                        exit 0
                    else
                        exit 1
                    fi

            -   name: "Run Tests"
                if: ${{env.RUN_TESTS == 'true'}}
                run: "cargo test"


    deploy:
        name: "Deploy Distributables on crates.io"
        env:
            working-directory: ${{github.workspace}}
        needs: ["test"]
        runs-on: "ubuntu-latest"

        steps:
            -   name: "Checkout Repository"
                uses: "actions/checkout@v4" # makes repository structure available

            -   name: "Install Rust"
                uses: "actions-rust-lang/setup-rust-toolchain@v1"
                with:
                    toolchain: ${{env.RUST_VERSION}}

            -   name: "Login to crates.io"
                run: "cargo login ${{secrets.CRATES_IO_TOKEN}}"

            -   name: "Publish to crates.io"
                run: "cargo publish"